version: "3"
services:
 docker-update:
  image: docker.clkl.de/docker/update:0.1_alpine
  build: .
  volumes:
   - ./docker-compose.py:/docker-compose.py
   - ./sample:/services
  command: bash -c 'python3 /docker_compose.py /services/*'