version: "3"
services:
 docker-update:
  image: docker.clkl.de/docker/update:0.1_alpine
  build: .
  volumes:
   - /opt/docker/services:/services
   - ./:/out/
  command: bash -c 'python3 /out/show_updateable.py -s -o /out/updates.json /services/* --ignore zammad'
