version: "2"

services:
  http:
    image: httpd:alpine
#    ports:
#      - "80:80"
    volumes:
      - /home/clemens/public_html/:/usr/local/apache2/htdocs/
    networks:
     - traefik_net
    labels:
     - "traefik.enable=true"
     - "traefik.docker.network=traefik_net"
     - "traefik.http.frontend.rule=Host:git24.example"
networks:
 traefik_net:
  external:
   name: traefik_net
